//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CARRO
    {
        public int Id { get; set; }
        public Nullable<int> AnoFabricacao { get; set; }
        public Nullable<int> AnoModelo { get; set; }
        public string Cor { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
    }
}
