//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTACIONAMNETO
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string NomeCliente { get; set; }
        public Nullable<int> Telefone { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public Nullable<System.DateTime> DataSaida { get; set; }
    }
}
